language: ruby
cache: bundler
rvm:
- 2.2.1
script: bundle exec rake test
notifications:
  email: false
env:
  global:
    - secure: "LUUnEhX/N8+0N4QB4hw0T5Ln+jV1JBsF5SR+ba0rTkfcY/lRXkhqxGZD7P5eJrIiX00ojjyuExQ0ACLnoMW+ZvAs6P1UvT2cfzvSuT0acMQWIj01M2X3iDEU9fovr3VZVD55rIO2EukjXxqtmm6SXng0ns7hjMu5qrpBBz/XonuDJeYpRlq6v1RhXpM5IJbCf36tx/wxrS37cerX/oXHXnASH0BqW2m3mncOLLb9xdwGj9GQShwTFkrk64jHP+lCRR1L0lYes9wNEzMayIOzNThyTVBYMP7Og19hRQMXU7USmW6sqiXIAV9OR6Mw44NsoUzgifzmcpG44lldutgBEvDGC3KauEZALFlUl6wV5Ccp0JBY+dKUaiP5kyAWJtI4HYkWkn/f2urENcmS2pzMBi7Tx2pvFpuDLXdDQR4BzW+53kVSqXJU98FByjg6DX13PYchcV4jb/CYheM6ZoKRWhAAc+S75tCA3uCeJjGoiuK3FHZvnjDQzOIJh66EA2AHqxj0FWyKVn1BGdA3y0jK5suyAXiVdSIfqFiTRVEKvUf3J3tzxhriWT/RPMTjsYEGvNTSZKhuUYlIZ4SxDaMgqQajQMoAgSXJ4VUkPv/faIZwYIl3H8KuMI9wsjU4+k+ZDyUzOx4xnze1gCW6on8TYo806uOiOUhL5q1VnBYckrY="
deploy_rubygems: &deploy_rubygems
  provider: rubygems
  api_key:
    secure: "bfgS0ra7Yi/60/eH+sxUspst0iA5j7Ez6jA58PIzPn/mXE47gM0f7vEI/yCLshxzpepoQZGW+XWPHMwerVTl6B31RP2ShMjggxIgOs703HQpElZ5E9T2/hz87CTvMRyp/ZSTwWnhjcqnbRGQvXohv/e6HmYOU08GztmvVlM3saweIUSrZUWgnfQvytY6BRmCsoknWnAJw0ikazVaQOURszQRS88xbZO+FraBMMDDCQlmyvptOkDnMNGDZXj760LCUKb4R0BgwfVNT0L/fOL/wEX+OMYGlTXfdYI6F8EZA41QbwUXij8d0okZr9TzsLAg//q4QHEWZKhEsmGP2nyo20z33ke/OD6eUA6e4EP5qH9kuRneHKCVrnyge9f/fNktfm/RdRYb4FGXiNR2o0Nv0ibXaKCY+HLW8FLXoEgHY8Re7GoFgsHE9qGD4Vs4n2sHPRU1uQRUMlVtZ43QLlUOII8q9Fu4NvzZfkNAtb4KhZQXtxPt8TQgrshMy420hv4Ve1Oc21D+3lnS2SYykX1v+b0eoU3vHzl+3cLpMUOvDRhwAWH1dZ0mOi2YNG+wwgK8gFjxpUHDAfTHCW9bims5KPUAsCWC9FWwuM1sm2glDPbddzomZjyvt0EkBv2k2mPOSx8JWTvZuCKPMmOuCA86g08U/ArqM0KDEqxg2H55FSk="
deploy:
  <<: *deploy_rubygems
  on:
    tags: true
deploy:
  <<: *deploy_rubygems
  on:
    branch: master
