language: ruby
cache: bundler
rvm:
- 2.2.1
script: bundle exec rake test
notifications:
  email: false
  slack:
    on_success: change
    on_failure: always
    on_start: change
    rooms:
      secure: ***REMOVED***
